name: IDROPONICA
description: A simple data logger that gets temperature and humidity from the board via Modulino Thermo and stores them in a database.
ports: []
bricks:
- arduino:dbstorage_tsstore: {}
- arduino:web_ui: {}
icon: 🌱
